# Generated by Django 5.2.4 on 2025-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_feed_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='is_bookmark',
            new_name='is_marked',
        ),
    ]
