name: CD-django-jinstagram

on:
  workflow_run:
    workflows: ["CI-django-jinstagram"]
    types:
      - completed

jobs:
  build:

    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          source django-jinstagram.sh
          git pull origin main
          source django-jinstagram.sh
          pip install -r requirements.txt
          
          sudo systemctl restart uwsgi